[build]
  publish = "."
  command = ""
  base = ""

[functions]
  directory = "netlify/functions"

[context.production]
  environment = { GAME_VERSION = "1.0.0", API_BASE_URL = "https://api.example.com" }